name: CubeCraftSpecialBow
version: BETA
main: me.liamhbest.cubecraftspecialbow.SpecialBow
api-version: 1.16
author: LiamHest
description: CubeCraft translation team developer application project.

commands:
  specialbow:
    aliases: [sb, sbow]
    description: Get the special bow